name: iOSplayground

settings:
  DEVELOPMENT_TEAM: 67762NVFY8
  PRODUCT_BUNDLE_IDENTIFIER: wakewakame.iOSplayground
  CODE_SIGN_STYLE: Automatic

targets:
  iOSplayground:
    sources: iOSplayground
    platform: iOS
    type: application
